### ISSUE TITLE
MAUI

### ISSUE THREAD

**Issue by stevehansen** [DouglasGiovanella/Xamarin.Android.Binding.InstallReferrer#4]
Does this package work on MAUI?

**Comment by gerneio** [comment]
@stevehansen Just wondering if you had found anything for MAUI yet?

**Comment by stevehansen** [comment]
@gerneio not yet unfortunately

**Comment by gerneio** [comment]
@stevehansen thanks for the quick response. I think I've had some luck and found this package [Xamarin.Google.Android.InstallReferrer](https://www.nuget.org/packages/Xamarin.Google.Android.InstallReferrer#dependencies-body-tab) that seems to work in MAUI. It's under the [Xamarin.AndroidX](https://github.com/xamarin/AndroidX/issues/494#issuecomment-1219316719) package suite by the looks of it (which MAUI already depends on?), and targets `net6.0-android31.0`, but does seem to be working in my `net7.0` MAUI app. The [example code](https://github.com/DouglasGiovanella/Xamarin.Android.Binding.InstallReferrer/blob/master/README.md#xamarinandroidbindinginstallreferrer) in this repo seems to match pretty closely to the other package, so I modified it and applied it to my `MainActivity` class, and well, it doesn't blow up (lol) and does make it all the way to the `OnConnectionEstablished` method! Just need to figure out how to test setting that `ReferrerDetails.InstallReferrer` string.

```csharp
using Xamarin.Android.InstallReferrer.Api;
// ...
public class MainActivity : MauiAppCompatActivity, IInstallReferrerStateListener
{
    InstallReferrerClient referrerClient;

    protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        referrerClient = InstallReferrerClient.NewBuilder(this).Build();

        referrerClient.StartConnection(this);
    }

    public void OnInstallReferrerSetupFinished(int code)
    {
        Console.WriteLine("OnInstallReferrerSetupFinished: ", code);

        switch (code)
        {
            case InstallReferrerClient.InstallReferrerResponse.DeveloperError:
                Console.WriteLine("InstallReferrerResponse: DeveloperError");
                break;
            //case InstallReferrerClient.InstallReferrerResponse.PermissionError:
            //    Console.WriteLine("InstallReferrerResponse: PermissionError");
            //    break;
            case InstallReferrerClient.InstallReferrerResponse.ServiceDisconnected:
                Console.WriteLine("InstallReferrerResponse: ServiceDisconnected");
                break;
            case InstallReferrerClient.InstallReferrerResponse.ServiceUnavailable:
                Console.WriteLine("InstallReferrerResponse: ServiceUnavailable");
                break;
            case InstallReferrerClient.InstallReferrerResponse.FeatureNotSupported:
                Console.WriteLine("InstallReferrerResponse: FeatureNotSupported");
                break;
            case InstallReferrerClient.InstallReferrerResponse.Ok:
                Console.WriteLine("InstallReferrerResponse: Ok");
                OnConnectionEstablished();
                break;
        }
    }

    private void OnConnectionEstablished()
    {
        ReferrerDetails response = referrerClient.InstallReferrer;
        string referrerUrl = response.InstallReferrer;

        // do something
        Console.WriteLine($"referrerUrl: {referrerUrl}");

        referrerClient?.EndConnection();
        referrerClient?.Dispose();
    }

    public void OnInstallReferrerServiceDisconnected()
    {
        Console.WriteLine("InstallReferrerServiceDisconnected");
    }
}
```

**Comment by gerneio** [comment]
FYI, I did get it to work all the way through, so the method above is solid.

**Comment by DouglasGiovanella** [comment]
Hello all
When i created this binding microsoft didn't had yet a official binding for this lib. With the .Net maui migration they created one over the AndroidX package suit as mentioned by @gerneio.

So that said, i will close this issue and archive this repo :)
